### ISSUE TITLE
copy drink

### ISSUE THREAD

**Issue by nicjohnson145** [nicjohnson145/mixer-remote#4]
when viewing another user's drinks, there should be a quick button to copy it to your own list. A super cool feature could be tracking upstream updates instead of "forking"

**Comment by jmgooden94** [comment]
this issue is closed by https://github.com/nicjohnson145/mixer-remote/commit/f1a9e1d2076ae122fa8482124137f64f97135cc3 but it seems I only have comment permissions on issues, not close
